<?php
/*
 * GonebusyLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace GonebusyLib;

use GonebusyLib\Controllers;

/**
 * GonebusyLib client class
 */
class GonebusyClient
{
    /**
     * Constructor with authentication and configuration parameters
     * @param  string $authorization API auth token string. Defaults to Configuration::$authorization
     * @param  boolean $debug whether to output REST debug info. Defaults to false.
     */
    public function __construct(
        $authorization = null,
        $debug = null
    ) {
        Configuration::$authorization = $authorization ? $authorization : Configuration::$authorization;

        Configuration::$debug = $debug ? true : false;
        if(Configuration::$debug)
            error_log(date('e Y-m-d H:s') . " REST debug enabled.\n", 3, Configuration::$debug_file);
    }

    /**
     * Singleton access to Bookings controller
     * @return Controllers\BookingsController The *Singleton* instance
     */
    public function getBookings()
    {
        return Controllers\BookingsController::getInstance();
    }

    /**
     * Singleton access to Categories controller
     * @return Controllers\CategoriesController The *Singleton* instance
     */
    public function getCategories()
    {
        return Controllers\CategoriesController::getInstance();
    }

    /**
     * Singleton access to PricingModels controller
     * @return Controllers\PricingModelsController The *Singleton* instance
     */
    public function getPricingModels()
    {
        return Controllers\PricingModelsController::getInstance();
    }

    /**
     * Singleton access to Resources controller
     * @return Controllers\ResourcesController The *Singleton* instance
     */
    public function getResources()
    {
        return Controllers\ResourcesController::getInstance();
    }

    /**
     * Singleton access to Schedules controller
     * @return Controllers\SchedulesController The *Singleton* instance
     */
    public function getSchedules()
    {
        return Controllers\SchedulesController::getInstance();
    }

    /**
     * Singleton access to Search controller
     * @return Controllers\SearchController The *Singleton* instance
     */
    public function getSearch()
    {
        return Controllers\SearchController::getInstance();
    }

    /**
     * Singleton access to Services controller
     * @return Controllers\ServicesController The *Singleton* instance
     */
    public function getServices()
    {
        return Controllers\ServicesController::getInstance();
    }

    /**
     * Singleton access to Users controller
     * @return Controllers\UsersController The *Singleton* instance
     */
    public function getUsers()
    {
        return Controllers\UsersController::getInstance();
    }
}
